#! /bin/sh
set -e

# This gives us the "linux_entry" command
source /etc/grub.d/10_linux > /dev/null 2>&1

for i in /boot/darch/* ; do
    linux="$i/vmlinuz-linux"
    gettext_printf "Found linux image: %s\n" "$linux" >&2
    basename=`basename $linux`
    dirname=`dirname $linux`
    rel_dirname=`make_system_path_relative_to_its_root $dirname`
    version=`echo $basename | sed -e "s,vmlinuz-,,g"`
    alt_version=`echo $version | sed -e "s,\.old$,,g"`
    linux_root_device_thisversion="${LINUX_ROOT_DEVICE}"
    initrd=initramfs-linux.img

    darch_source_block_device=`df --output=source $i | tail -1`
    darch_source_uuid=`blkid $darch_source_block_device | sed -n 's/.* UUID=\"\([^\"]*\)\".*/\1/p'`
    darch_source_absolute=`echo ${i#$(df $i --output=target | tail -1)}`
    darch_cmdline="darchdir=UUID=$darch_source_uuid:$darch_source_absolute"
    linux_entry "Darch - $(basename $i)" "${version}" "simple" "${GRUB_CMDLINE_LINUX} ${GRUB_CMDLINE_LINUX_DEFAULT} $darch_cmdline"
done