#!/bin/bash
set -e

# Let's build the base Docker image.
# This image is a runnable Arch image, but it won't be used for much.
# Inside of the image will be a /rootfs that will be updating.
docker build --no-cache -t darch-arch-rootfs-builder .
