#!/bin/bash
set -e

# Prepare our rootfs.tar.gz file.
./combine-rootfs

# Let's build the base Docker image.
# This image is a runnable Arch image, but it won't be used for much.
# Inside of the image will be a /rootfs that will be updating.
docker build -t darch-arch-rootfs-builder .
