#! /bin/sh
set -e

# This will add the code required to load /etc/darch/grub.cfg.
# This allows us to update /etc/darch/grub.cfg safely, without
# fear of ruining our base boot.
darch stage grub config-entry